# Loki Configuration for Snaproom Logging System
# Production-ready configuration with security and performance optimizations

auth_enabled: false # Set to true for multi-tenant environments

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s
  http_server_idle_timeout: 120s

# Common configuration shared across components
common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

# Query frontend configuration for better performance
query_scheduler:
  max_outstanding_requests_per_tenant: 256

frontend:
  max_outstanding_per_tenant: 256
  compress_responses: true
  downstream_url: http://localhost:3100

query_range:
  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        max_size_bytes: 1GB
        validity: 24h

# Ingester configuration optimized for performance
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
    num_tokens: 512

  # Chunk configuration for optimal performance
  chunk_idle_period: 30m # Reduced from 1h for faster processing
  max_chunk_age: 1h # Keep at 1h for balance
  chunk_target_size: 1572864 # 1.5MB target size
  chunk_retain_period: 30s
  max_transfer_retries: 0 # Disabled for single-node setup

  # WAL configuration for data durability
  wal:
    enabled: true
    dir: /loki/wal
    checkpoint_duration: 5m
    flush_on_shutdown: true

# Schema configuration using TSDB for better performance
schema_config:
  configs:
    # Legacy schema for backwards compatibility (must come first chronologically)
    - from: 2020-04-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: legacy_index_
        period: 24h

    # Current schema using TSDB (recommended for new installations)
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v12
      index:
        prefix: snaproom_index_
        period: 24h

# Storage configuration with performance optimizations
storage_config:
  tsdb_shipper:
    active_index_directory: /loki/tsdb-shipper-active
    cache_location: /loki/tsdb-shipper-cache
    cache_ttl: 24h
    shared_store: filesystem
    index_gateway_client:
      server_address: dns:///localhost:9095

  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: filesystem

  filesystem:
    directory: /loki/chunks

# Compactor for storage optimization
compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

# Limits configuration for production stability
limits_config:
  # Ingestion limits
  ingestion_rate_mb: 4 # 4MB/s per tenant
  ingestion_burst_size_mb: 6 # 6MB burst
  max_streams_per_user: 10000 # Max streams per tenant
  max_line_size: 256KB # Max line size

  # Retention and cleanup
  reject_old_samples: true
  reject_old_samples_max_age: 168h # 7 days
  creation_grace_period: 10m

  # Query limits
  max_query_parallelism: 32
  max_query_series: 500
  max_query_lookback: 720h # 30 days

  # Per-stream limits
  per_stream_rate_limit: 3MB
  per_stream_rate_limit_burst: 15MB

  # Cardinality limits
  max_global_streams_per_user: 5000
  max_chunks_per_query: 2000000

# Chunk store configuration
chunk_store_config:
  max_look_back_period: 0s
  chunk_cache_config:
    enable_fifocache: true
    fifocache:
      max_size_bytes: 1GB
      validity: 24h

# Table manager with retention enabled
table_manager:
  retention_deletes_enabled: true
  retention_period: 720h # 30 days retention
  poll_interval: 2m
  creation_grace_period: 3h
  index_tables_provisioning:
    inactive_read_throughput: 300
    inactive_write_throughput: 1
    provisioned_read_throughput: 300
    provisioned_write_throughput: 3000
  chunk_tables_provisioning:
    inactive_read_throughput: 300
    inactive_write_throughput: 1
    provisioned_read_throughput: 300
    provisioned_write_throughput: 3000

# Ruler configuration for alerting
ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
  enable_alertmanager_v2: true
  enable_sharding: false
  evaluation_interval: 1m
  poll_interval: 1m

# Analytics configuration
analytics:
  reporting_enabled: false

# Tracing configuration (optional)
tracing:
  enabled: false
