global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'snaproom-logging-monitor'
    environment: 'development'

# Rule files for alerting
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Alerting configuration (if AlertManager is available)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Self monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s

  # Snaproom logging collector
  - job_name: 'snaproom-logging-collector'
    static_configs:
      - targets: ["collector:8080"]
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'logging-collector'
      - source_labels: [__address__]
        target_label: service
        replacement: 'logging-collector'
      - target_label: team
        replacement: 'devops'

  # Loki metrics (if available)
  - job_name: 'loki'
    static_configs:
      - targets: ["loki:3100"]
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Grafana metrics (if available)  
  - job_name: 'grafana'
    static_configs:
      - targets: ["grafana:3000"]
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Legacy job name for backwards compatibility
  - job_name: 'logging'
    static_configs:
      - targets: ["collector:8080"]
    scrape_interval: 15s
