# AlertManager Configuration for Snaproom MSA
global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@snaproom.com'
  smtp_auth_username: 'alerts@snaproom.com'
  smtp_auth_password: 'your_smtp_password'
  slack_api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'

# Templates for alert formatting
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route tree for alert routing
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'web.hook'
  routes:
    # Critical alerts go to PagerDuty and Slack
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 30s
      group_interval: 2m
      repeat_interval: 1h
      continue: true

    # Backend team alerts
    - match:
        team: backend
      receiver: 'backend-team'
      group_wait: 1m
      group_interval: 5m
      repeat_interval: 2h

    # DevOps team alerts
    - match:
        team: devops
      receiver: 'devops-team'
      group_wait: 1m
      group_interval: 5m
      repeat_interval: 2h

    # Security team alerts
    - match:
        team: security
      receiver: 'security-team'
      group_wait: 30s
      group_interval: 2m
      repeat_interval: 1h

    # Product team alerts
    - match:
        team: product
      receiver: 'product-team'
      group_wait: 5m
      group_interval: 10m
      repeat_interval: 4h

# Inhibition rules to suppress notifications
inhibit_rules:
  # Suppress warning alerts if critical alert is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

  # Suppress individual service alerts if general service down alert is firing
  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: '.*(High|Low).*'
    equal: ['instance']

# Alert receivers
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'webhook_user'
            password: 'webhook_password'

  - name: 'critical-alerts'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#critical-alerts'
        title: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Service:* {{ .Labels.service }}
          *Instance:* {{ .Labels.instance }}
          {{ end }}
        send_resolved: true
        color: 'danger'
    # email_configs:
    #   - to: 'critical-alerts@snaproom.com'
    #     subject: '[CRITICAL] {{ .GroupLabels.alertname }}'
    #     body: |
    #       {{ range .Alerts }}
    #       Alert: {{ .Annotations.summary }}
    #       Description: {{ .Annotations.description }}
    #       Severity: {{ .Labels.severity }}
    #       Service: {{ .Labels.service }}
    #       Instance: {{ .Labels.instance }}
    #       {{ end }}

  - name: 'backend-team'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#backend-alerts'
        title: '⚠️ Backend Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Service:* {{ .Labels.service }}
          {{ end }}
        send_resolved: true
        color: 'warning'

  - name: 'devops-team'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#devops-alerts'
        title: '🔧 Infrastructure Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Instance:* {{ .Labels.instance }}
          {{ end }}
        send_resolved: true
        color: '#36a64f'

  - name: 'security-team'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#security-alerts'
        title: '🛡️ Security Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          {{ end }}
        send_resolved: true
        color: 'danger'

  - name: 'product-team'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#product-alerts'
        title: '📊 Business Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          {{ end }}
        send_resolved: true
        color: '#2eb886'